### PR TITLE
closes #11, adds function for adding k/v pairs to cookie

### LINKED ISSUE #11: SPA: JS Cookie Name/Encrypted-Password Addition Callback
Accepts a key/value pair and adds the pair to the app's cookie for service names/encrypted-passwords

### PR DESCRIPTION
**Pull request by Shiggiddie**

### CODE REVIEW

**Comment by anthony-dandrea** [comment]
@Shiggiddie Does this work? `document.cookie` is not JSON but a string rather. For example GH's cookie is `"_octo=GH1.1.1794218867.1426109996; tz=America%2FLos_Angeles; _ga=GA1.2.995397001.1426531963; _gat=1"` which isn't JSON-y at all.

Here's some js functions I wrote earlier today that work for setting cookies and getting the value of a cookie.

```
// expires by default when browser is closed can be set for different time
// cookie defaults for use on the page path it is on when set
var setCookie = function(key, value) {
    document.cookie = key + '=' + value + ';';
};
```

```
// yourcookiekey is equal to what cookie you're looking for
// couldnt find a nice way to make it dynamic with a param because JS is weird
// when converting strings to regex
var cookieValue = function(key) {
    var cookieVal = (document.cookie.match(/^(?:.*;)?yourcookiekey=([^;]+)(?:.*)?$/)||[,null])[1];
    return cookieVal
}
```

This [SO](http://stackoverflow.com/questions/5968196/check-cookie-if-cookie-exists/25617724#25617724) post was helpful for me.

**Comment by DLavin23** [comment]
Also, I used this recently and it was super easy/lightweight https://github.com/js-cookie/js-cookie/blob/master/README.md

**Comment by anthony-dandrea** [comment]
Fixed the second function in my original post to take keys as a param properly and add it to the regex. I was being retarded before.

```
// Accepts key param
// returns value of key or null if no cookie set
var cookieValue = function(key) {
    var regexKey = "^(?:.*;)?"+key+"=([^;]+)(?:.*)?$"
    regexKey = new RegExp(regexKey);
    return (document.cookie.match(regexKey)||[,null])[1];
}
```

**Comment by Shiggiddie** [comment]
+1 on all dis.  I dun fucked up on the cookie concept because I neglected to recall that they are stored as a string `name=value`.

In that sense, we'll need to parse the cookie initially to pull out the `name=` portion of the cookie.

It is worth noting, however, that the `value` of the cookie will be a stringified JSON object.  Therefore, once we get the `value` after parsing the cookie, we'll want to run that value through `JSON.parse`.

**Pull request merged**
